### ISSUE TITLE
table auth_user has no column named is_managed

### ISSUE THREAD

**Issue by khinze** [slafs/sentry-docker#15]
Hi Slafs,

I tried to install sentry again on another server I have. 

These are the steps I followed. 
curl -sSL https://get.docker.com/ubuntu/ | sudo sh

docker run -d --name=sentry --volume=/tmp/sentry:/data -p 9000:9000 -e SECRET_KEY=mykey -e SENTRY_URL_PREFIX=http://mydomain.com slafs/sentry

The docker logs is as below. 

/usr/local/bin/sentry_run: line 37:     5 Killed                  sentry --config=$SENTRY_CONF_FILE upgrade --noinput
spawn sentry --config=/conf/sentry_docker_conf.py createsuperuser --username=admin --email=root@localhost
[WARNING] /usr/local/lib/python2.7/site-packages/sentry/utils/runner.py:322: UserWarning: Sentry is configured to run asynchronous tasks in-process. This is not recommended within production environments. See http://sentry.readthedocs.org/en/latest/queue/index.html for more information.
  warnings.warn('Sentry is configured to run asynchronous tasks in-process. '

Password: 
Password (again): 
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 414, in main
    initializer=initialize_app,
  File "/usr/local/lib/python2.7/site-packages/logan/runner.py", line 169, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 141, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 195, in create_superuser
    **extra_fields)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 186, in _create_user
    user.save(using=self._db)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/user.py", line 63, in save
    return super(User, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table auth_user has no column named is_managed
[WARNING] /usr/local/lib/python2.7/site-packages/sentry/utils/runner.py:322: UserWarning: Sentry is configured to run asynchronous tasks in-process. This is not recommended within production environments. See http://sentry.readthedocs.org/en/latest/queue/index.html for more information.
  warnings.warn('Sentry is configured to run asynchronous tasks in-process. '

[WARNING] /usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.last_seen received a naive datetime (2015-03-02 09:23:29.205377) while time zone support is active.
  RuntimeWarning)

[WARNING] /usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.first_seen received a naive datetime (2015-03-02 09:23:29.208771) while time zone support is active.
  RuntimeWarning)

[WARNING] /usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.last_seen received a naive datetime (2015-03-02 09:23:29.209630) while time zone support is active.
  RuntimeWarning)

[WARNING] /usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.first_seen received a naive datetime (2015-03-02 09:23:29.226174) while time zone support is active.
  RuntimeWarning)

/usr/local/bin/sentry_run: line 41:    20 Killed                  sentry --config=$SENTRY_CONF_FILE $@

**Comment by slafs** [comment]
wow this is weird. Are you sure ``/tmp/sentry`` was empty before running the container for the first time?

**Comment by khinze** [comment]
After it didnt work the first time. What I did do is delete the sentry folder and the container and loaded it again. I see the sentry.db there however no log files.

**Comment by slafs** [comment]
So the logs above are from the first or the second run? it seems that the migrations didn't ended well. I just ran your command and it worked fine. Try this: ``docker run --rm -it --name=sentry --volume=/tmp/sentry:/data -p 9000:9000 -e SECRET_KEY=mykey -e SENTRY_URL_PREFIX=http://mydomain.com slafs/sentry``

**Comment by khinze** [comment]
Second time.

Steps I did: docker rm mycontainer
your command. 

root@staging:~# docker run --rm -it --name=sentry --volume=/tmp/sentry:/data -p 9000:9000 -e SECRET_KEY=* -e SENTRY_URL_PREFIX=http://*.com slafs/sentry
[WARNING] /usr/local/lib/python2.7/site-packages/sentry/utils/runner.py:322: UserWarning: Sentry is configured to run asynchronous tasks in-process. This is not recommended within production environments. See http://sentry.readthedocs.org/en/latest/queue/index.html for more information.
  warnings.warn('Sentry is configured to run asynchronous tasks in-process. '

Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for djcelery:
- Nothing to migrate.
 - Loading initial data for djcelery.
Installed 0 object(s) from 0 fixture(s)
Running migrations for django:
- Nothing to migrate.
 - Loading initial data for django.
Installed 0 object(s) from 0 fixture(s)
Running migrations for sentry:
 - Migrating forwards to 0156_auto__add_apikey.
 > sentry:0067_auto__add_field_group_platform__add_field_event_platform
 > sentry:0068_auto__add_field_projectkey_user_added__add_field_projectkey_date_added
[WARNING] /usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.date_added received a naive datetime (2015-03-02 12:10:53.081500) while time zone support is active.
  RuntimeWarning)

[WARNING] /usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.date_added received a naive datetime (2015-03-02 12:10:53.099594) while time zone support is active.
  RuntimeWarning)

 > sentry:0069_auto__add_lostpasswordhash
 > sentry:0070_projectoption_key_length
 > sentry:0071_auto__add_field_group_users_seen
 > sentry:0072_auto__add_affecteduserbygroup__add_unique_affecteduserbygroup_project_
 > sentry:0073_auto__add_field_project_platform
 > sentry:0074_correct_filtervalue_index
 > sentry:0075_add_groupbookmark_index
 > sentry:0076_add_groupmeta_index
 > sentry:0077_auto__add_trackeduser__add_unique_trackeduser_project_ident
 > sentry:0078_auto__add_field_affecteduserbygroup_tuser
/usr/local/bin/sentry_run: line 37:     5 Killed                  sentry --config=$SENTRY_CONF_FILE upgrade --noinput
spawn sentry --config=/conf/sentry_docker_conf.py createsuperuser --username=admin --email=root@localhost
[WARNING] /usr/local/lib/python2.7/site-packages/sentry/utils/runner.py:322: UserWarning: Sentry is configured to run asynchronous tasks in-process. This is not recommended within production environments. See http://sentry.readthedocs.org/en/latest/queue/index.html for more information.
  warnings.warn('Sentry is configured to run asynchronous tasks in-process. '

Password: 
Password (again): 
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 414, in main
    initializer=initialize_app,
  File "/usr/local/lib/python2.7/site-packages/logan/runner.py", line 169, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 141, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 195, in create_superuser
    **extra_fields)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 186, in _create_user
    user.save(using=self._db)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/user.py", line 63, in save
    return super(User, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table auth_user has no column named is_managed
[WARNING] /usr/local/lib/python2.7/site-packages/sentry/utils/runner.py:322: UserWarning: Sentry is configured to run asynchronous tasks in-process. This is not recommended within production environments. See http://sentry.readthedocs.org/en/latest/queue/index.html for more information.
  warnings.warn('Sentry is configured to run asynchronous tasks in-process. '

Performing upgrade before service startup...
/usr/local/bin/sentry_run: line 41:    20 Killed                  sentry --config=$SENTRY_CONF_FILE $@

**Comment by slafs** [comment]
Yeah. As I said. I'm pretty sure something went wrong for the first time and now ``/tmp/sentry`` has an inconsistent database file. Try deleting it and rerun the command. Use some external service for pasting your logs (like http://pastebin.com/) since pasting it here is unparsable for me.

**Comment by khinze** [comment]
Steps: 
cd /tmp
rm -rf sentry
ls... no sentry present. 

same error ...

http://pastebin.com/V83ZbJYZ

**Comment by slafs** [comment]
This sooo weird. Although I'm still not convinced. The error is not the same. As you can see there are no migrations info for sentry in your logs and now the table ``auth_user`` wasn't even created.

Show me also your:

``docker info``

and

``docker images | grep sentry``

**Comment by khinze** [comment]
root@staging:~# docker info
Containers: 0
Images: 28
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 28
Execution Driver: native-0.2
Kernel Version: 3.8.0-29-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 1
Total Memory: 491 MiB
Name: staging
ID: YL6I:NK6P:N2QY:SXYO:REW3:P4VX:M7IX:5FB5:GZPG:EZRE:KSZK:XIEZ
WARNING: No swap limit support

**Comment by khinze** [comment]
slafs/sentry        latest              a7f505914cd8        6 days ago          967.2 MB

**Comment by slafs** [comment]
I'm clueless. It seems like something external is killing the process while the script is trying to create the database. You should probably double check if maybe kernel isn't killing the process because it's running out of resources or something like that. 491MB of memory sounds alarming. I guess that's my best shot on this.

**Comment by khinze** [comment]
:) Thanks Slafs. I really appreciate your help. I'll see if I can figure it out and then i'll let you know what it was.

**Comment by khinze** [comment]
When I go to the /usr/local/bin there is no file named sentry. 

The database does get created. /tmp/sentry/sentry.db. so when its running migration scripts it must be killing the process.

**Comment by slafs** [comment]
I don't think I get it. The script inside the container is called ``/usr/local/bin/sentry_run``

**Comment by slafs** [comment]
closing for now. feel free to reopen
