### ISSUE TITLE
Connection error to Redis

### ISSUE THREAD

**Issue by adamlc** [slafs/sentry-docker#39]
Not sure whats happening here? My redis instance is linked and all the ENV variables are setup correctly.

Heres the error after the migrations run:

```
[ERROR] Error 111 connecting to None:6379. Connection refused.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 150, in __post_save
    cache.set(self.__get_lookup_cache_key(**{pk_name: pk_val}), instance, self.cache_ttl)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django_redis/cache.py", line 30, in _decorator
    raise e.parent
ConnectionError: Error 111 connecting to None:6379. Connection refused.
Top level Sentry exception caught - failed creating log record
Error 111 connecting to None:6379. Connection refused.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/raven/handlers/logging.py", line 65, in emit
    return self._emit(record)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/handlers.py", line 29, in _emit
    return super(SentryHandler, self)._emit(record, request=request)
  File "/usr/local/lib/python2.7/site-packages/raven/handlers/logging.py", line 176, in _emit
    extra=extra, date=date, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 39, in capture
    return super(SentryInternalClient, self).capture(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 157, in capture
    result = super(DjangoClient, self).capture(event_type, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/raven/base.py", line 521, in capture
    self.send(**data)
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 50, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/usr/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 207, in get_from_cache
    retval = cache.get(cache_key)
  File "/usr/local/lib/python2.7/site-packages/sentry/../django_redis/cache.py", line 30, in _decorator
    raise e.parent
ConnectionError: Error 111 connecting to None:6379. Connection refused.
```

Having a quick google reveals that it might be something to do with django-redis?

**Comment by slafs** [comment]
And you want me to take your word on it only? ;) Please provide the settings you are using.

**Comment by adamlc** [comment]
Haha! Probably would have helped if I included it :+1: 

```
docker run -d \
    --name=sentry \
    --link=sentry_postgres:postgresdb \
    --link=sentry_redis:redis \
    -e "VIRTUAL_HOST=REMOVED" \
    -e "SECRET_KEY=REMOVED" \
    -e "SENTRY_URL_PREFIX=https://REMOVED" \
    -e "DATABASE_URL=postgres://postgres:@postgresdb/postgres" \
    -e "CACHE_URL=hiredis://redis:6379/2/" \
    -e "SENTRY_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend" \
    -e "SENTRY_EMAIL_HOST=smtp.mandrillapp.com" \
    -e "SENTRY_EMAIL_PORT=587" \
    -e "SENTRY_EMAIL_HOST_USER=REMOVED" \
    -e "SENTRY_EMAIL_HOST_PASSWORD=REMOVED" \
    -e "SENTRY_SERVER_EMAIL=REMOVED" \
    -e "SENTRY_USE_REDIS_TSDB=True" \
    -e "SENTRY_USE_REDIS_BUFFERS=True" \
    -e "SENTRY_ALLOW_ORIGIN=True" \
    -e "CELERY_ALWAYS_EAGER=False" \
     --restart=always \
    slafs/sentry:7.7
```

**Comment by slafs** [comment]
Yep. Change `hiredis://redis:6379/2/` to `hiredis://redis:6379/2` (remove the trailing slash). It's an issue both in `django-redis` and `django-cache-url`. This should help.

**Comment by adamlc** [comment]
That works perfectly! Thanks @slafs :)

**Comment by croepha** [comment]
This one got me too....  for people in the future, is there any thing that could be done, like, version pinning for django-redis or django-cache-url or maybe some assertion checks?

**Comment by slafs** [comment]
Not sure. `django-redis` changed the way how it treats locations and `django-cache-url` doesn't support it yet. I've started working on adding support for new `django-redis` format in `django-cache-url` but they've changed structure of code quite a bit since then (releasing 1.0). 

Feel free to add a warning message in `environment.example` or `README` as a Pull Request ;)

**Comment by slafs** [comment]
There https://github.com/slafs/sentry-docker/commit/19b1fcd6964ad8426545fe96bc8e4b1ec456875f :)

**Comment by croepha** [comment]
Nice!
