### ISSUE TITLE
Cannot syncdb on the first run

### ISSUE THREAD

**Issue by andreycizov** [slafs/sentry-docker#41]
Full log output:

```Syncing...
11/12/2015 6:24:01 PMCreating tables ...
11/12/2015 6:24:01 PMInstalling custom SQL ...
11/12/2015 6:24:01 PMInstalling indexes ...
11/12/2015 6:24:01 PMInstalled 0 object(s) from 0 fixture(s)
11/12/2015 6:24:01 PMMigrating...
11/12/2015 6:24:02 PMRunning migrations for django:
11/12/2015 6:24:02 PM- Nothing to migrate.
11/12/2015 6:24:02 PM - Loading initial data for django.
11/12/2015 6:24:02 PMInstalled 0 object(s) from 0 fixture(s)
11/12/2015 6:24:02 PMRunning migrations for sentry:
11/12/2015 6:24:03 PM - Migrating forwards to 0213_migrate_file_blobs.
11/12/2015 6:24:03 PM > sentry:0061_auto__add_field_group_group_id__add_field_group_is_public
11/12/2015 6:24:03 PM > sentry:0062_correct_del_index_sentry_groupedmessage_logger__view__checksum
11/12/2015 6:24:03 PM > sentry:0063_auto
11/12/2015 6:24:03 PM > sentry:0064_index_checksum
11/12/2015 6:24:03 PM > sentry:0065_create_default_project_key
11/12/2015 6:24:03 PM > sentry:0066_auto__del_view
11/12/2015 6:24:03 PM > sentry:0067_auto__add_field_group_platform__add_field_event_platform
11/12/2015 6:24:03 PM > sentry:0068_auto__add_field_projectkey_user_added__add_field_projectkey_date_added
11/12/2015 6:24:03 PM[WARNING] /usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.date_added received a naive datetime (2015-11-12 18:24:03.916683) while time zone support is active.
11/12/2015 6:24:03 PM  RuntimeWarning)
11/12/2015 6:24:03 PM
11/12/2015 6:24:03 PM > sentry:0069_auto__add_lostpasswordhash
11/12/2015 6:24:04 PM > sentry:0070_projectoption_key_length
11/12/2015 6:24:04 PM > sentry:0071_auto__add_field_group_users_seen
11/12/2015 6:24:04 PM > sentry:0072_auto__add_affecteduserbygroup__add_unique_affecteduserbygroup_project_
11/12/2015 6:24:04 PM > sentry:0073_auto__add_field_project_platform
11/12/2015 6:24:04 PM > sentry:0074_correct_filtervalue_index
11/12/2015 6:24:04 PM > sentry:0075_add_groupbookmark_index
11/12/2015 6:24:04 PM > sentry:0076_add_groupmeta_index
11/12/2015 6:24:04 PM > sentry:0077_auto__add_trackeduser__add_unique_trackeduser_project_ident
11/12/2015 6:24:04 PM > sentry:0078_auto__add_field_affecteduserbygroup_tuser
11/12/2015 6:24:05 PM > sentry:0079_auto__del_unique_affecteduserbygroup_project_ident_group__add_unique_a
11/12/2015 6:24:05 PM > sentry:0080_auto__chg_field_affecteduserbygroup_ident
11/12/2015 6:24:05 PM > sentry:0081_fill_trackeduser
11/12/2015 6:24:05 PM > sentry:0082_auto__add_activity__add_field_group_num_comments__add_field_event_num_
11/12/2015 6:24:05 PM > sentry:0083_migrate_dupe_groups
11/12/2015 6:24:05 PM > sentry:0084_auto__del_unique_group_project_checksum_logger_culprit__add_unique_gro
11/12/2015 6:24:06 PM > sentry:0085_auto__del_unique_project_slug__add_unique_project_slug_team
11/12/2015 6:24:06 PM > sentry:0086_auto__add_field_team_date_added
11/12/2015 6:24:06 PM[WARNING] /usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.date_added received a naive datetime (2015-11-12 18:24:06.169427) while time zone support is active.
11/12/2015 6:24:06 PM  RuntimeWarning)
11/12/2015 6:24:06 PM
11/12/2015 6:24:06 PM > sentry:0087_auto__del_messagefiltervalue__del_unique_messagefiltervalue_project_ke
11/12/2015 6:24:06 PM > sentry:0088_auto__del_messagecountbyminute__del_unique_messagecountbyminute_projec
11/12/2015 6:24:06 PM > sentry:0089_auto__add_accessgroup__add_unique_accessgroup_team_name
11/12/2015 6:24:06 PM > sentry:0090_auto__add_grouptagkey__add_unique_grouptagkey_project_group_key__add_f
11/12/2015 6:24:06 PM[WARNING] /usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.last_seen received a naive datetime (2015-11-12 18:24:06.491398) while time zone support is active.
11/12/2015 6:24:06 PM  RuntimeWarning)
11/12/2015 6:24:06 PM
11/12/2015 6:24:06 PM[WARNING] /usr/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.first_seen received a naive datetime (2015-11-12 18:24:06.503414) while time zone support is active.
11/12/2015 6:24:06 PM  RuntimeWarning)
11/12/2015 6:24:06 PM
11/12/2015 6:24:06 PM > sentry:0091_auto__add_alert
11/12/2015 6:24:06 PM > sentry:0092_auto__add_alertrelatedgroup__add_unique_alertrelatedgroup_group_alert
11/12/2015 6:24:06 PM > sentry:0093_auto__add_field_alert_status
11/12/2015 6:24:07 PM > sentry:0094_auto__add_eventmapping__add_unique_eventmapping_project_event_id
11/12/2015 6:24:15 PM/usr/local/bin/sentry_run: line 38:     6 Killed                  sentry --config=$SENTRY_CONF_FILE upgrade --noinput
11/12/2015 6:24:18 PMTraceback (most recent call last):
11/12/2015 6:24:18 PM  File "/conf/create_team_or_project.py", line 139, in <module>
11/12/2015 6:24:18 PM    main()
11/12/2015 6:24:18 PM  File "/conf/create_team_or_project.py", line 136, in main
11/12/2015 6:24:18 PM    create_admin(username, email, password)
11/12/2015 6:24:18 PM  File "/conf/create_team_or_project.py", line 33, in create_admin
11/12/2015 6:24:18 PM    admin = User.objects.create_superuser(username=username, email=email, password=password)
11/12/2015 6:24:18 PM  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 195, in create_superuser
11/12/2015 6:24:18 PM    **extra_fields)
11/12/2015 6:24:18 PM  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 186, in _create_user
11/12/2015 6:24:18 PM    user.save(using=self._db)
11/12/2015 6:24:18 PM  File "/src/sentry/src/sentry/models/user.py", line 69, in save
11/12/2015 6:24:18 PM    return super(User, self).save(*args, **kwargs)
11/12/2015 6:24:18 PM  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
11/12/2015 6:24:18 PM    force_update=force_update, update_fields=update_fields)
11/12/2015 6:24:18 PM  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
11/12/2015 6:24:18 PM    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
11/12/2015 6:24:18 PM  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
11/12/2015 6:24:18 PM    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
11/12/2015 6:24:18 PM  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
11/12/2015 6:24:18 PM    using=using, raw=raw)
11/12/2015 6:24:18 PM  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
11/12/2015 6:24:18 PM    return insert_query(self.model, objs, fields, **kwargs)
11/12/2015 6:24:18 PM  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
11/12/2015 6:24:18 PM    return query.get_compiler(using=using).execute_sql(return_id)
11/12/2015 6:24:18 PM  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
11/12/2015 6:24:18 PM    cursor.execute(sql, params)
11/12/2015 6:24:18 PM  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
11/12/2015 6:24:18 PM    return self.cursor.execute(sql, params)
11/12/2015 6:24:18 PM  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
11/12/2015 6:24:18 PM    six.reraise(dj_exc_type, dj_exc_value, traceback)
11/12/2015 6:24:18 PM  File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
11/12/2015 6:24:18 PM    return self.cursor.execute(sql, params)
11/12/2015 6:24:18 PMdjango.db.utils.ProgrammingError: column "is_managed" of relation "auth_user" does not exist
11/12/2015 6:24:18 PMLINE 1: ..."email", "is_staff", "is_active", "is_superuser", "is_manage...
11/12/2015 6:24:18 PM                                                             ^
11/12/2015 6:24:18 PM
11/12/2015 6:24:22 PMRunning service: 'http'```

**Comment by andreycizov** [comment]
This error happens if you run the web worker under memory limits that are lower than expected during ```django-admin migrate```.
