### ISSUE TITLE
logan.importer.ConfigurationError with latest image

### ISSUE THREAD

**Issue by felixonmars** [slafs/sentry-docker#44]
I am getting the following error repeatedly and Sentry doesn't start. any hints?

```
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 448, in main
    initializer=initialize_app,
  File "/usr/local/lib/python2.7/site-packages/logan/runner.py", line 191, in run_app
    configure_app(config_path=config_path, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/logan/runner.py", line 127, in configure_app
    allow_extras=allow_extras, callback=settings_callback)
  File "/usr/local/lib/python2.7/site-packages/logan/importer.py", line 37, in install
    sys.meta_path.append(LoganImporter(name, config_path, default_settings, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/logan/importer.py", line 52, in __init__
    self.validate()
  File "/usr/local/lib/python2.7/site-packages/logan/importer.py", line 66, in validate
    raise ConfigurationError(unicode(e), exc_info[2])
logan.importer.ConfigurationError: (u'cannot import name _uuid_generate_random', <traceback object at 0x7f7fc719d830>)
```

**Comment by slafs** [comment]
That's weird... I have no idea where this came from :/

**Comment by slafs** [comment]
ah :/ it's probably this https://github.com/celery/kombu/issues/545

**Comment by slafs** [comment]
Made a quickfix in 17dca0b63.

Please verify if it's working for you now.

**Comment by felixonmars** [comment]
Works fine now. Thanks!
