### ISSUE TITLE
Creating a superuser fails when database is already provisioned

### ISSUE THREAD

**Issue by TheSavior** [slafs/sentry-docker#52]
In my startup logs, I get the following error when reconnecting to a database that has already been set up:

```
spawn sentry --config=/conf/sentry_docker_conf.py createsuperuser --username=admin --email=root@localhost
Password: 
Password (again): 
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 435, in main
    initializer=initialize_app,
  ...
django.db.utils.IntegrityError: duplicate key value violates unique constraint "auth_user_username_key"
DETAIL:  Key (username)=(admin) already exists.

```

**Comment by slafs** [comment]
This shouldn't be an issue in general, nothing wrong happens besides creating this superuser (which is already created) and the script continues its work. The way how a superuser is created was changed in version `7.7.1` of this image.
